/**
 * Static Command Registry — read-only whitelist for the Command Palette.
 *
 * Only commands with riskLevel="read" are included in this MVP registry.
 * The old MAESTRO_TOOL_CATALOG in maestro-mcp-provider.ts is preserved
 * unchanged and still used by the MCP provider for its own purposes.
 *
 * This registry is the data source for the tRPC commands.list procedure.
 */

import type { CommandDefinition } from "./types";

// ---------------------------------------------------------------------------
// Read-only command registry
// ---------------------------------------------------------------------------

export const COMMAND_REGISTRY: readonly CommandDefinition[] = [
  // -- ralph ---------------------------------------------------------------
  {
    id: "ralph-skills",
    label: "cmd.ralph_skills",
    category: "ralph",
    cliCommand: "maestro",
    cliArgs: ["ralph", "skills"],
    description: "cmd.ralph_skills.desc",
    outputKind: "table",
    riskLevel: "read",
  },
  {
    id: "ralph-check",
    label: "cmd.ralph_check",
    category: "ralph",
    cliCommand: "maestro",
    cliArgs: ["ralph", "check"],
    description: "cmd.ralph_check.desc",
    outputKind: "text",
    riskLevel: "read",
  },
  {
    id: "ralph-session",
    label: "cmd.ralph_session",
    category: "ralph",
    cliCommand: "maestro",
    cliArgs: ["ralph", "session"],
    description: "cmd.ralph_session.desc",
    outputKind: "json",
    riskLevel: "read",
  },

  // -- knowledge -----------------------------------------------------------
  {
    id: "knowledge-search",
    label: "cmd.knowledge_search",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["search", "<query>"],
    description: "cmd.knowledge_search.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "knowledge-load",
    label: "cmd.knowledge_load",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["load", "--type", "<type>", "[--category", "<category>]"],
    description: "cmd.knowledge_load.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "spec-load",
    label: "cmd.spec_load",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["spec", "load", "--category", "<category>"],
    description: "cmd.spec_load.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "knowhow-search",
    label: "cmd.knowhow_search",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["knowhow", "search", "<query>"],
    description: "cmd.knowhow_search.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "wiki-search",
    label: "cmd.wiki_search",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["wiki", "search", "<query>"],
    description: "cmd.wiki_search.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "wiki-health",
    label: "cmd.wiki_health",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["wiki", "health"],
    description: "cmd.wiki_health.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "wiki-graph",
    label: "cmd.wiki_graph",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["wiki", "graph"],
    description: "cmd.wiki_graph.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "domain-list",
    label: "cmd.domain_list",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["domain", "list"],
    description: "cmd.domain_list.desc",
    outputKind: "table",
    riskLevel: "read",
  },
  {
    id: "kg-query",
    label: "cmd.kg_query",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["kg", "search", "<query>"],
    description: "cmd.kg_query.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "kg-context",
    label: "cmd.kg_context",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["kg", "context", "<node>"],
    description: "cmd.kg_context.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "kg-callers",
    label: "cmd.kg_callers",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["kg", "callers", "<fn>"],
    description: "cmd.kg_callers.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "kg-callees",
    label: "cmd.kg_callees",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["kg", "callees", "<fn>"],
    description: "cmd.kg_callees.desc",
    outputKind: "json",
    riskLevel: "read",
  },

  // -- project -------------------------------------------------------------
  {
    id: "milestone-audit",
    label: "cmd.milestone_audit",
    category: "project",
    cliCommand: "maestro",
    cliArgs: ["milestone", "audit"],
    description: "cmd.milestone_audit.desc",
    outputKind: "table",
    riskLevel: "read",
  },
  {
    id: "manage-status",
    label: "cmd.manage_status",
    category: "project",
    cliCommand: "maestro",
    cliArgs: ["manage", "status"],
    description: "cmd.manage_status.desc",
    outputKind: "state",
    riskLevel: "read",
  },
  {
    id: "manage-issue-discover",
    label: "cmd.manage_issue_discover",
    category: "project",
    cliCommand: "maestro",
    cliArgs: ["issue:discover", "<context>"],
    description: "cmd.manage_issue_discover.desc",
    outputKind: "json",
    riskLevel: "read",
  },

  // -- debug ---------------------------------------------------------------
  {
    id: "security-audit",
    label: "cmd.security_audit",
    category: "debug",
    cliCommand: "maestro",
    cliArgs: ["security-audit", "<target>"],
    description: "cmd.security_audit.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "learn-follow",
    label: "cmd.learn_follow",
    category: "debug",
    cliCommand: "maestro",
    cliArgs: ["learn-follow", "<topic>"],
    description: "cmd.learn_follow.desc",
    outputKind: "text",
    riskLevel: "read",
  },
  {
    id: "learn-investigate",
    label: "cmd.learn_investigate",
    category: "debug",
    cliCommand: "maestro",
    cliArgs: ["learn-investigate", "<question>"],
    description: "cmd.learn_investigate.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "learn-second-opinion",
    label: "cmd.learn_second_opinion",
    category: "debug",
    cliCommand: "maestro",
    cliArgs: ["learn-second-opinion", "<question>"],
    description: "cmd.learn_second_opinion.desc",
    outputKind: "text",
    riskLevel: "read",
  },

  // -- system --------------------------------------------------------------
  {
    id: "explore",
    label: "cmd.explore",
    category: "system",
    cliCommand: "maestro",
    cliArgs: ["explore", "<prompt>"],
    description: "cmd.explore.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "workspace-list",
    label: "cmd.workspace_list",
    category: "system",
    cliCommand: "maestro",
    cliArgs: ["workspace", "list"],
    description: "cmd.workspace_list.desc",
    outputKind: "table",
    riskLevel: "read",
  },

  // -- config --------------------------------------------------------------
  {
    id: "overlay-list",
    label: "cmd.overlay_list",
    category: "config",
    cliCommand: "maestro",
    cliArgs: ["overlay", "list"],
    description: "cmd.overlay_list.desc",
    outputKind: "table",
    riskLevel: "read",
  },
  {
    id: "hooks-status",
    label: "cmd.hooks_status",
    category: "config",
    cliCommand: "maestro",
    cliArgs: ["hooks", "status"],
    description: "cmd.hooks_status.desc",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "delegate-show",
    label: "cmd.delegate_show",
    category: "config",
    cliCommand: "maestro",
    cliArgs: ["delegate", "show", "<id>"],
    description: "cmd.delegate_show.desc",
    outputKind: "json",
    riskLevel: "read",
  },
] as const;
