/**
 * Static Command Registry — read-only whitelist for the Command Palette.
 *
 * Only commands with riskLevel="read" are included in this MVP registry.
 * The old MAESTRO_TOOL_CATALOG in maestro-mcp-provider.ts is preserved
 * unchanged and still used by the MCP provider for its own purposes.
 *
 * This registry is the data source for the tRPC commands.list procedure.
 */

import type { CommandDefinition } from "./types";

// ---------------------------------------------------------------------------
// Read-only command registry
// ---------------------------------------------------------------------------

export const COMMAND_REGISTRY: readonly CommandDefinition[] = [
  // -- ralph ---------------------------------------------------------------
  {
    id: "ralph-skills",
    label: "Ralph 技能列表",
    category: "ralph",
    cliCommand: "maestro",
    cliArgs: ["ralph", "skills"],
    description: "列出 Ralph 可用的技能和角色配置",
    outputKind: "table",
    riskLevel: "read",
  },
  {
    id: "ralph-check",
    label: "Ralph 状态检查",
    category: "ralph",
    cliCommand: "maestro",
    cliArgs: ["ralph", "check"],
    description: "检查 Ralph 连接状态和配置",
    outputKind: "text",
    riskLevel: "read",
  },
  {
    id: "ralph-session",
    label: "Ralph 会话信息",
    category: "ralph",
    cliCommand: "maestro",
    cliArgs: ["ralph", "session"],
    description: "查看当前 Ralph 会话信息",
    outputKind: "json",
    riskLevel: "read",
  },

  // -- knowledge -----------------------------------------------------------
  {
    id: "knowledge-search",
    label: "知识搜索",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["search", "<query>"],
    description: "跨 spec、knowhow、wiki、代码的语义搜索",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "knowledge-load",
    label: "知识加载",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["load", "--type", "<type>", "[--category", "<category>]"],
    description: "按类型和分类加载知识条目",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "spec-load",
    label: "Spec 加载",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["spec", "load", "--category", "<category>"],
    description: "按分类加载项目 spec 条目",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "knowhow-search",
    label: "Knowhow 搜索",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["knowhow", "search", "<query>"],
    description: "搜索 knowhow 知识条目",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "wiki-search",
    label: "Wiki 搜索",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["wiki", "search", "<query>"],
    description: "搜索 wiki 文档",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "wiki-health",
    label: "Wiki 健康检查",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["wiki", "health"],
    description: "检查 wiki 系统健康状态",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "wiki-graph",
    label: "Wiki 图谱",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["wiki", "graph"],
    description: "查看 wiki 知识图谱结构",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "domain-list",
    label: "领域列表",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["domain", "list"],
    description: "列出所有领域定义",
    outputKind: "table",
    riskLevel: "read",
  },
  {
    id: "kg-query",
    label: "KG 查询",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["kg", "search", "<query>"],
    description: "直接查询知识图谱符号",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "kg-context",
    label: "KG 上下文",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["kg", "context", "<node>"],
    description: "获取知识图谱节点的上下文信息",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "kg-callers",
    label: "KG 调用者",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["kg", "callers", "<fn>"],
    description: "查找函数的所有调用者",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "kg-callees",
    label: "KG 被调用者",
    category: "knowledge",
    cliCommand: "maestro",
    cliArgs: ["kg", "callees", "<fn>"],
    description: "查找函数调用的所有子函数",
    outputKind: "json",
    riskLevel: "read",
  },

  // -- project -------------------------------------------------------------
  {
    id: "milestone-audit",
    label: "里程碑审计",
    category: "project",
    cliCommand: "maestro",
    cliArgs: ["milestone", "audit"],
    description: "审计项目里程碑完成状态",
    outputKind: "table",
    riskLevel: "read",
  },
  {
    id: "manage-status",
    label: "项目状态",
    category: "project",
    cliCommand: "maestro",
    cliArgs: ["manage", "status"],
    description: "查看项目当前状态概览",
    outputKind: "state",
    riskLevel: "read",
  },
  {
    id: "manage-issue-discover",
    label: "问题发现",
    category: "project",
    cliCommand: "maestro",
    cliArgs: ["issue:discover", "<context>"],
    description: "从多视角发现潜在问题",
    outputKind: "json",
    riskLevel: "read",
  },

  // -- debug ---------------------------------------------------------------
  {
    id: "security-audit",
    label: "安全审计",
    category: "debug",
    cliCommand: "maestro",
    cliArgs: ["security-audit", "<target>"],
    description: "OWASP Top 10 和 STRIDE 安全审计",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "learn-follow",
    label: "学习跟踪",
    category: "debug",
    cliCommand: "maestro",
    cliArgs: ["learn-follow", "<topic>"],
    description: "跟踪学习主题进展",
    outputKind: "text",
    riskLevel: "read",
  },
  {
    id: "learn-investigate",
    label: "假设调查",
    category: "debug",
    cliCommand: "maestro",
    cliArgs: ["learn-investigate", "<question>"],
    description: "假设驱动的调查和证据记录",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "learn-second-opinion",
    label: "第二意见",
    category: "debug",
    cliCommand: "maestro",
    cliArgs: ["learn-second-opinion", "<question>"],
    description: "从不同角度获取第二意见",
    outputKind: "text",
    riskLevel: "read",
  },

  // -- system --------------------------------------------------------------
  {
    id: "explore",
    label: "代码探索",
    category: "system",
    cliCommand: "maestro",
    cliArgs: ["explore", "<prompt>"],
    description: "多角度代码库扫描和发现",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "workspace-list",
    label: "工作区列表",
    category: "system",
    cliCommand: "maestro",
    cliArgs: ["workspace", "list"],
    description: "列出所有可用工作区",
    outputKind: "table",
    riskLevel: "read",
  },

  // -- config --------------------------------------------------------------
  {
    id: "overlay-list",
    label: "覆盖层列表",
    category: "config",
    cliCommand: "maestro",
    cliArgs: ["overlay", "list"],
    description: "列出配置覆盖层",
    outputKind: "table",
    riskLevel: "read",
  },
  {
    id: "hooks-status",
    label: "钩子状态",
    category: "config",
    cliCommand: "maestro",
    cliArgs: ["hooks", "status"],
    description: "查看钩子配置状态",
    outputKind: "json",
    riskLevel: "read",
  },
  {
    id: "delegate-show",
    label: "委派详情",
    category: "config",
    cliCommand: "maestro",
    cliArgs: ["delegate", "show", "<id>"],
    description: "查看委派任务详情",
    outputKind: "json",
    riskLevel: "read",
  },
] as const;
