/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  createFileRoute,
  type CreateFileRoute,
} from '@tanstack/react-router'
import { Route as rootRouteImport } from './routes/__root'

// Module augmentation — must come first so createFileRoute can resolve types
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: '/_authenticated'
      fullPath: '/_authenticated'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/v2-workspace/$workspaceId': {
      id: '/v2-workspace/$workspaceId'
      path: '/v2-workspace/$workspaceId'
      fullPath: '/v2-workspace/$workspaceId'
      preLoaderRoute: typeof V2WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

// Virtual route nodes (no physical route files exist yet)
const AuthenticatedLayoutRouteImport = createFileRoute('/_authenticated')()
const SettingsLayoutRouteImport = createFileRoute('/settings')()
const SettingsAgentsRouteImport = createFileRoute('/settings/agents')()
const SettingsAccountRouteImport = createFileRoute('/settings/account')()
const SettingsModelsRouteImport = createFileRoute('/settings/models')()
const TasksTaskIdRouteImport = createFileRoute('/tasks/$taskId')()
const WorkspaceRouteImport = createFileRoute('/workspace')()
const WorkspacesWorkspaceIdRouteImport = createFileRoute('/workspaces/$workspaceId')()
const V2WorkspaceWorkspaceIdRouteImport = createFileRoute('/v2-workspace/$workspaceId')()

// Route update declarations
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)

const SettingsLayoutRoute = SettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/settings/agents',
  path: '/agents',
  getParentRoute: () => SettingsLayoutRoute,
} as any)

const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/account',
  getParentRoute: () => SettingsLayoutRoute,
} as any)

const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/settings/models',
  path: '/models',
  getParentRoute: () => SettingsLayoutRoute,
} as any)

const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

const V2WorkspaceWorkspaceIdRoute = V2WorkspaceWorkspaceIdRouteImport.update({
  id: '/v2-workspace/$workspaceId',
  path: '/v2-workspace/$workspaceId',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsLayoutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/models': typeof SettingsModelsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workspace': typeof WorkspaceRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/v2-workspace/$workspaceId': typeof V2WorkspaceWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsLayoutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/models': typeof SettingsModelsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workspace': typeof WorkspaceRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/v2-workspace/$workspaceId': typeof V2WorkspaceWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedLayoutRoute
  '/settings': typeof SettingsLayoutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/models': typeof SettingsModelsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workspace': typeof WorkspaceRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/v2-workspace/$workspaceId': typeof V2WorkspaceWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/settings' | '/settings/agents' | '/settings/account' | '/settings/models' | '/tasks/$taskId' | '/workspace' | '/workspaces/$workspaceId' | '/v2-workspace/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/settings/agents' | '/settings/account' | '/settings/models' | '/tasks/$taskId' | '/workspace' | '/workspaces/$workspaceId' | '/v2-workspace/$workspaceId'
  id: '__root__' | '/_authenticated' | '/settings' | '/settings/agents' | '/settings/account' | '/settings/models' | '/tasks/$taskId' | '/workspace' | '/workspaces/$workspaceId' | '/v2-workspace/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
